import type { Product } from './product';

export const productFixtures = [
  {
    id: 'pink-tomatoes',
    name: 'Томаты розовые',
    category: 'vegetables',
    categoryLabel: 'Овощи',
    description:
      'Сочные розовые томаты с насыщенным ароматом. Отлично подойдут для салатов и брускетт.',
    priceKopecks: 27_900,
    oldPriceKopecks: 34_900,
    unit: '500 г',
    badge: '−20%',
    emoji: '🍅',
    accent: 'tomato',
  },
  {
    id: 'hass-avocado',
    name: 'Авокадо Хасс',
    category: 'vegetables',
    categoryLabel: 'Овощи',
    description:
      'Мягкое спелое авокадо с кремовой текстурой для завтраков, тостов и салатов.',
    priceKopecks: 19_900,
    oldPriceKopecks: null,
    unit: '2 шт.',
    badge: 'Спелое',
    emoji: '🥑',
    accent: 'avocado',
  },
  {
    id: 'mini-bananas',
    name: 'Бананы мини',
    category: 'fruits',
    categoryLabel: 'Фрукты',
    description: 'Сладкие мини-бананы без терпкости — удобно взять с собой.',
    priceKopecks: 16_900,
    oldPriceKopecks: null,
    unit: '500 г',
    badge: null,
    emoji: '🍌',
    accent: 'banana',
  },
  {
    id: 'farm-milk',
    name: 'Молоко фермерское',
    category: 'dairy',
    categoryLabel: 'Молочное',
    description: 'Пастеризованное молоко с мягким сливочным вкусом.',
    priceKopecks: 12_900,
    oldPriceKopecks: null,
    unit: '930 мл',
    badge: 'Новинка',
    emoji: '🥛',
    accent: 'milk',
  },
  {
    id: 'almond-croissant',
    name: 'Круассан миндальный',
    category: 'bakery',
    categoryLabel: 'Выпечка',
    description: 'Воздушный круассан с миндальным кремом и хрустящими лепестками.',
    priceKopecks: 15_900,
    oldPriceKopecks: 18_900,
    unit: '120 г',
    badge: '−16%',
    emoji: '🥐',
    accent: 'pastry',
  },
  {
    id: 'garden-strawberry',
    name: 'Клубника садовая',
    category: 'fruits',
    categoryLabel: 'Фрукты',
    description: 'Ароматная сладкая клубника, отобранная вручную.',
    priceKopecks: 38_900,
    oldPriceKopecks: null,
    unit: '250 г',
    badge: 'Хит',
    emoji: '🍓',
    accent: 'berry',
  },
  {
    id: 'blueberry-yogurt',
    name: 'Йогурт с черникой',
    category: 'dairy',
    categoryLabel: 'Молочное',
    description: 'Натуральный йогурт с цельными ягодами черники.',
    priceKopecks: 9_900,
    oldPriceKopecks: null,
    unit: '180 г',
    badge: null,
    emoji: '🫐',
    accent: 'yogurt',
  },
  {
    id: 'artisan-bread',
    name: 'Хлеб ремесленный',
    category: 'bakery',
    categoryLabel: 'Выпечка',
    description: 'Пшеничный хлеб на закваске с хрустящей корочкой.',
    priceKopecks: 17_900,
    oldPriceKopecks: null,
    unit: '400 г',
    badge: null,
    emoji: '🥖',
    accent: 'bread',
  },
  {
    id: 'selected-oranges',
    name: 'Апельсины отборные',
    category: 'fruits',
    categoryLabel: 'Фрукты',
    description: 'Сочные апельсины с яркой кислинкой и тонкой кожурой.',
    priceKopecks: 21_900,
    oldPriceKopecks: null,
    unit: '1 кг',
    badge: null,
    emoji: '🍊',
    accent: 'orange',
  },
  {
    id: 'apple-juice',
    name: 'Сок яблочный прямой отжим',
    category: 'drinks',
    categoryLabel: 'Напитки',
    description: 'Нефильтрованный яблочный сок без добавленного сахара.',
    priceKopecks: 24_900,
    oldPriceKopecks: null,
    unit: '1 л',
    badge: 'Без сахара',
    emoji: '🧃',
    accent: 'juice',
  },
  {
    id: 'medium-cucumbers',
    name: 'Огурцы среднеплодные',
    category: 'vegetables',
    categoryLabel: 'Овощи',
    description: 'Хрустящие огурцы с тонкой кожицей и свежим ароматом.',
    priceKopecks: 18_900,
    oldPriceKopecks: null,
    unit: '600 г',
    badge: null,
    emoji: '🥒',
    accent: 'cucumber',
  },
  {
    id: 'raspberry-kombucha',
    name: 'Комбуча малина',
    category: 'drinks',
    categoryLabel: 'Напитки',
    description: 'Освежающий ферментированный напиток с малиновым соком.',
    priceKopecks: 17_900,
    oldPriceKopecks: 19_900,
    unit: '330 мл',
    badge: '−10%',
    emoji: '🍹',
    accent: 'kombucha',
  },
] satisfies Product[];
